### ISSUE TITLE
Function which extracts a JSON based on a SHACL definition

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-validate-shacl#1]
Loosly based on [UC42](https://www.w3.org/TR/shacl-ucr/#uc42:-constraining-rdf-graphs-to-provide-better-mapping-to-json).

Create a function which takes
1. An entry point (root node) term inside a dataset.
1. SHACL description provided with a term inside a dataset.
and outputs a JSON structure described by the SHACL description.

`.asJson(rootTerm, shaclTerm, shaclDataset)`

**Comment by martinmaillard** [comment]
Would it be possible to provide sample data (turtle), sample shapes (turtle) and the output that you would expect? That would help me a lot.

**Comment by martinmaillard** [comment]
@l00mi Reminder ;)

**Comment by l00mi** [comment]
The following example is not an attempt to find all edge cases but is a starting point.

It shows the input data (taken from https://www.w3.org/TR/vcard-rdf/) and an example of the Output. I do not know how the SHACL would need to look like to be able to get to this transformation, @bergos do you have any idea on that?

# Input Data
```
@base <http://example.com/me/> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
<corky> a vcard:Individual;
vcard:fn "Corky Crystal"; vcard:hasAddress <corky#address>; vcard:hasTelephone <corky#telephone>; vcard:nickname "Corks".
<corky#telephone> a vcard:Home, a vcard:Voice; vcard:hasValue "tel:+61755555555".
<corky#address> a vcard:Home; vcard:country-name "Australia"; vcard:locality "WonderCity"; vcard:postal-code "5555"; vcard:street-address "111 Lake Drive".
```

# Output
```
{
	"address": {
		"location_link": [{
			"location": {
				"city": {
					"locality": "WonderCity",
					"postal-code": "5555",
					"country-name": "Australia"
				},
				"street-address": "111 Lake Drive"
			}
		}]
	},
	"aka": {
		"fn": "Corky Crystal",
		"nickname": "Corks"
	}
}
```


Both structures visualised, left the graph, right the output.
<img width="727" alt="Screenshot 2020-03-24 at 17 29 39" src="https://user-images.githubusercontent.com/502518/77453727-e8e6a200-6df7-11ea-9ef1-ce3c2c9a4374.png">


For context, the goal of this transformation was to use this template:
```
  <div>
      <span class="glyphicon glyphicon-envelope" style="font-size:48px; float:left; margin: 0 15px 0 10px;"></span>
      <div>
      <b>{{address.aka.fn}}</b> [aka {{address.aka.nickname}}]<br>
      {{address.location_link.0.location.street-address}}<br>
      {{address.location_link.0.location.city.locality}} {{address.location_link.0.location.city.postal-code}}
      <span style="text-transform:uppercase;">{{address.location_link.0.location.city.country-name}}</span>
      </div>
  </div>
```

<img width="279" alt="Screenshot 2020-03-24 at 17 52 25" src="https://user-images.githubusercontent.com/502518/77454009-47138500-6df8-11ea-8d41-48622a16bf95.png">

**Comment by martinmaillard** [comment]
I'll close this, as it does not really fit the scope of this library. By the way, I already have some version of this function in another project ;)
