### ISSUE TITLE
Cyclic references lead to "too much recursion"

### ISSUE THREAD

**Issue by s-tittel** [zazuko/rdf-validate-shacl#136]
Hi and thanks for you great library.

When validating a data graph that contains cyclic references (e.g. hasPart / isPartOf relations), I get:
```
Uncaught (in promise) InternalError: too much recursion
```

Here is an example to reproduce: https://s.zazuko.com/SiL9iY

Edit: I would suggest employing a method similar to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#use_case_detecting_circular_references).

**Comment by ktk** [comment]
Thanks for the report, pull-requests would be welcome.

You might also try out this one (not by us): https://github.com/rdf-ext/shacl-engine

**Comment by s-tittel** [comment]
Could you please review the [PR](https://github.com/zazuko/rdf-validate-shacl/pull/137)?

**Comment by s-tittel** [comment]
thanks!
