### ISSUE TITLE
Rules on parent class are not being applied.

### ISSUE THREAD

**Issue by gruhnow** [zazuko/rdf-validate-shacl#142]
I created a playground to reproduce the issue [here](https://shacl-playground.zazuko.com/#shapesGraph=%40prefix+%3A+%3Chttp%3A%2F%2Fexample.org%2Fontology%23%3E+.%0A%40prefix+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+.%0A%40prefix+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E+.%0A%40prefix+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E+.%0A%40prefix+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E+.%0A%40prefix+sh%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0A%0A%3AhasName+a+owl%3ADatatypeProperty+%3B%0A++++rdfs%3Adomain+%3AAnimal+%3B%0A++++rdfs%3Arange+xsd%3Astring+%3B%0A++++rdfs%3Alabel+%22has+name%22+%3B%0A++++rdfs%3Acomment+%22Specifies+the+name+of+an+animal.%22%3B%0A.%0A%0A%3AAnimal+a+rdfs%3AClass%2C+sh%3ANodeShape+%3B%0A++++rdfs%3Alabel+%22Animal%22+%3B%0A++++rdfs%3Acomment+%22A+general+class+for+all+animals.%22+%3B%0A%09sh%3Aproperty+%5B%0A++++++rdf%3Atype+sh%3APropertyShape+%3B%0A++++++sh%3Apath+%3AhasName+%3B%0A++++++sh%3Adatatype+xsd%3Astring+%3B%0A++++++sh%3AminCount+1+%3B%0A++++%5D+%3B%0A.%0A%0A%3ADog+a+rdfs%3AClass%2C+sh%3ANodeShape+%3B%0A++++rdfs%3AsubClassOf+%3AAnimal+%3B%0A++++rdfs%3Alabel+%22Dog%22+%3B%0A++++rdfs%3Acomment+%22A+class+for+all+dogs.%22+%3B%0A.%0A&dataGraph=%40prefix+%3A+%3Chttp%3A%2F%2Fexample.org%2Fontology%23%3E+.%0A%40prefix+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+.%0A%40prefix+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E+.%0A%40prefix+dc%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E+.%0A%40prefix+vcard%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23%3E+.%0A%40prefix+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E+.%0A%40prefix+sh%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0A%3ABuddy+a+%3ADog+%3B%0A%23++++%3AhasName+%22Buddy%22+%3B%0A++++%3AhasVaccinationStatus+true+.%0A&shapesGraphFormat=text%2Fturtle&dataGraphFormat=text%2Fturtle).
Constraints:
```ttl
@prefix : <http://example.org/ontology#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .


:hasName a owl:DatatypeProperty ;
    rdfs:domain :Animal ;
    rdfs:range xsd:string ;
    rdfs:label "has name" ;
    rdfs:comment "Specifies the name of an animal.";
.

:Animal a rdfs:Class, sh:NodeShape ;
    rdfs:label "Animal" ;
    rdfs:comment "A general class for all animals." ;
	sh:property [
      rdf:type sh:PropertyShape ;
      sh:path :hasName ;
      sh:minCount 1 ;
    ] ;
.


:Dog a rdfs:Class, sh:NodeShape ;
    rdfs:subClassOf :Animal ;
    rdfs:label "Dog" ;
    rdfs:comment "A class for all dogs." ;
.

```

Shapes:
```ttl
@prefix : <http://example.org/ontology#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

:Buddy a :Dog ;
#    :hasName "Buddy" ;
    :hasVaccinationStatus true .

```

Based on @HolgerKnublauch 's comments [here](https://github.com/zazuko/rdf-validate-shacl/issues/41#issuecomment-745803630) I'd expect constraint validation to fail because Buddy does not have a name which is required by the animal class. Am I missing something?

**Comment by tpluscode** [comment]
Thank you for reporting. I would have to look at the code to confirm but I think we may not currently implement sub classes.

(You did forget `:Mammal rdfs:subClassOf :Animal` but it does not change the outcome)

**Comment by gruhnow** [comment]
@tpluscode Nice catch! I simplified my example for the issue, but broke it in the process. I've updated the link to a fixed example.

**Comment by gruhnow** [comment]
I'll have to dig more since I'm not familiar with the code base, but it looks like [getInstances](https://github.com/zazuko/rdf-validate-shacl/blob/master/src/dataset-utils.js#L65) calls [getInstancesOf](https://github.com/zazuko/rdf-validate-shacl/blob/master/src/dataset-utils.js#L65) which is supposed to collect sub classes.

**Comment by giacomociti** [comment]
the triple `:Dog rdfs:subClassOf :Animal .` should be in the data graph. See also https://github.com/w3c/data-shapes/issues/155

**Comment by tpluscode** [comment]
@giacomociti the updated playground link simpifies to only Dog and Animal but the validation still passes 🤔

**Comment by tpluscode** [comment]
Thanks @giacomociti for pointing that out. With this change, the playground example indeed works

I suppose we should close this issue then, lest we intend to deviate from the spec

**Comment by gruhnow** [comment]
Thank you for the clarification @giacomociti! Closing.
