### ISSUE TITLE
[Question] How to use the DataFactory provided by N3

### ISSUE THREAD

**Issue by MMesch** [zazuko/rdf-validate-shacl#143]
Is it possible to use the `DataFactory` object from the [N3](https://github.com/rdfjs/N3.js?tab=readme-ov-file#creating-triplesquads) library?

When I naively try `new SHACLValidator(shapes, { factory: DataFactory });` I get:

```
Type 'typeof DataFactory' is not assignable to type 'Factory<Quad, Quad, DatasetCore<Quad, Quad>>'.
  Property 'dataset' is missing in type 'typeof DataFactory' but required in type 'DatasetCoreFactory<Quad, Quad, DatasetCore<Quad, Quad>>'. (tsserver 2322)
```

It did work well for me with [rdf-ext](https://github.com/rdf-ext/rdf-ext) but I wanted to avoid converting quad objects back and forth and also the extra dependency if possible.

I am not super experienced with Typescript. Any idea how to fix or work around this?

**Comment by MMesch** [comment]
Fixed using this new factory instead:

```
export const ExtendedDataFactory = {
	...DataFactory,
	dataset: quadsToN3Store
}

export function quadsToN3Store(quads: Quad[]): Store {
	return new Store(quads);
}
```

N3 also has a DataSetCoreFactory since recently (see https://github.com/rdfjs/N3.js/issues/314 and https://github.com/rdfjs/N3.js/pull/398/files) but I struggled to use it since it's implemented as a class static function and I (beginner in Typescript, sorry) don't know how to efficiently combine that class with the DatasetFactory required by the SHACLValidator constructor.

**Comment by tpluscode** [comment]
Hello @MMesch. I'm glad you found a workaround. 

Turns out that N3 types published from Definitely Types do not yet export the store. (PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70364)

In the future, I would like to be able to use N3 factories with RDF/JS Environment like,

```js
import SHACLValidator from 'rdf-validate-shacl'
import { DataFactory, StoreFactory } from 'n3'
import Environment from '@rdfjs/environment'

const factory = new Environment([DataFactory, StoreFactory])

const validator = new SHACLValidator(shapes, { factory })
```

That, however, will require some changes in n3
