### ISSUE TITLE
API: ValidationReport

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/rdf-validate-shacl#2]
According to the spec, the validation process should return a graph that contains a `sh:ValidationReport`.

To be compliant, we could just return a `Dataset` that contains the report.

However, the original author of this lib took the decision to return a `ValidationReport` object that makes it easier to use the report (`.conforms()`, `.results()`, etc.). I think that makes sense, but the graph should still be accessible from the returned object.

My first intuition would be to keep the `ValidationReport` object as return value, but to add a `.dataset` or `.graph` property on it that provides access to the graph. But I don't know if it fits usual patterns in the RDF world.

@bergos do you have an opinion on what we should return?

**Comment by bergos** [comment]
I would propose to add a *graph pointer* data structure, like it's used in clowface, rdf-path and the loaders. The full pointer structure would be `{ dataset, term, graph }`, but we can skip the `graph` property now and add it later with the rest of the named graph support. The `dataset` property would be then the dataset of the result. The `term` property would be the root of the report.
