### ISSUE TITLE
SHACL-JS

### ISSUE THREAD

**Issue by alex-randles** [zazuko/rdf-validate-shacl#28]
Hi,

Two questions, would you have an example I can run? I'm having trouble running the code in the readme.md as I'm unsure of the correct way to pass the shapes and data file into the SHACL validator. I tried the following, passing the file name as a string argument but this wont work. 

`const validator = new SHACLValidator('function.ttl')
const report = validator.validate('data.ttl')`

Also does your implementation support SHACL-JS extension?

**Comment by martinmaillard** [comment]
Hey there,

I will add a working example in the README today, that should help.

> Also does your implementation support SHACL-JS extension?

No, it only supports SHACL-core at the moment.

**Comment by ktk** [comment]
@randlea2 regarding SHACL-JS: That is an unofficial spec and it is not using the [RDFJS](http://rdf.js.org/) interface. Holger recently mentioned in a conversation that SHACL-JS extensions should be aligned to RDFJS as well.

Once this is done we could consider implementing it but in the current state it does not make much sense.

**Comment by martinmaillard** [comment]
I added a working example in the README. Not that if your SHACL shapes contain blank nodes, you might encounter an issue (see #25). We are working on it ;)
