### ISSUE TITLE
Feature request: add TypeScript types?

### ISSUE THREAD

**Issue by persona0591** [zazuko/rdf-validate-shacl#35]
Hi all!

Thanks for this great library! :)

Would it be possible to add a declaration file with TypeScript types?

**Comment by ktk** [comment]
Hi,

Thanks for the kind words! We won't do TS declarations in this repo though. For those who want TS definitions we recommend adding support for our libraries at http://definitelytyped.org/

**Comment by persona0591** [comment]
Hi Adrian, I understand - thank you!
