### ISSUE TITLE
Display sh:message in output

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-validate-shacl#39]
There is support for [sh:message](https://www.w3.org/TR/shacl/#message) in the specification so one can add human readable explanations of the constraint.

It seems like this message is not passed to the report at the moment. Would be great to have that to improve the understanding of the problem.

**Comment by tpluscode** [comment]
Please share an example of a shape and invalid graph. We've found that the message does get added but only in some scenarios

**Comment by ktk** [comment]
Now you mention it I noticed that on that particular node I did not had a message, sorry about!

I was expecting the followup message as it was on a different shape but that's obviously not the case because it did not even get there yet (on that particular shape). So all looks good at the moment, I will re-open in case I find a swallowed mesage.
