### ISSUE TITLE
Customization of default failure messages

### ISSUE THREAD

**Issue by Gnomus042** [zazuko/rdf-validate-shacl#40]
Is there any opportunity for specifying custom failure messages for different types of failures (texts, that are defined in validators-registry.js)? I want to add localization to my project, so I need to replace these messages with translated ones. Thank you in advance for the answer :)

**Comment by ktk** [comment]
@Gnomus042 You can provide custom labels with `sh:message`, I used that quite a lot recently and it was enough for me to define "proper" texts about what is wrong and you can explicitly translate those, see the [specification](https://www.w3.org/TR/shacl/#message). Is that enough?

**Comment by Gnomus042** [comment]
Should be fine, thanks!
