### ISSUE TITLE
Unsure whether dash and SPARQL selects are implemented

### ISSUE THREAD

**Issue by holycrab13** [zazuko/rdf-validate-shacl#68]
Is targeting via SPARQL implemented? If so, what might I be doing wrong?
My Shapes Graph:
```
@prefix dash: <http://datashapes.org/dash#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

<http://example.org/shapes> owl:imports <http://datashapes.org/dash> .

<http://example.org/shapes#allblanks>
	a sh:NodeShape ;
	sh:target dash:AllObjects ;
	sh:nodeKind sh:BlankNodeOrIRI .
```

My Data Graph

```
@prefix dc: <http://purl.org/dc/terms/> .

<https://some.uri.org> dc:title "Hello World"@en .
```

This yields SUCCESS while I am trying to make this fail - I want to verify that all objects are either blanks or IRIs (no Literals allowed).

I have read that SPARQL-based Constraints are not implemented, was unsure about SPARQL-based Targets

**Comment by ktk** [comment]
I don't think that's implemented, which spec is that?

**Comment by martinmaillard** [comment]
This is currently not supported. Closing.
