### ISSUE TITLE
Export property path matching

### ISSUE THREAD

**Issue by pietercolpaert** [zazuko/rdf-validate-shacl#71]
Also for other use cases than validation I want to be able, from an array of quads, extract the rdfjs.Terms that match the property path:

```typescript
matchPropertyPath<RDFJS.Term> (quads: RDFJS.Quad[], subject: RDFJS.Term, path: PropertyPath);
```

I assume the function on L61 in https://github.com/zazuko/rdf-validate-shacl/blob/master/src/property-path.js#L61 comes pretty close to what I need. Can this functionality be exported separately in this NPM package?

**Comment by tpluscode** [comment]
I think you might be interested in [clownface-shacl-path](https://npm.im/clownface-shacl-path)
