### ISSUE TITLE
Wrong pair constraint comparison using lessThan / lessThanOrEquals

### ISSUE THREAD

**Issue by Tomas2D** [zazuko/rdf-validate-shacl#83]
Using property constraint validation with `sh:lessThan` or `sh:lessThanOrEquals` I get wrong result in Zazuko SHACL Plaground ([https://s.zazuko.com/d56u3](https://s.zazuko.com/d56u3)). 

From my observation, it looks like only the first digit is being compared. For example, if the value of `ex:candidates_active` is `65`, there is no validation error which is obviously fine, but when I change to `8` or `9`, I get a validation error.

Thanks in advance.

**Comment by martinmaillard** [comment]
I just found this comment in the term comparison function: `// TODO: Does not handle numeric or date comparison`

It's been in the library from the beginning and somehow got overlooked. I'll label this issue as a bug.

**Comment by Tomas2D** [comment]
Do you plan to fix this?
